import { LOCATION_COORDS } from "./shipmentCoords";

// U.S. states → 2-letter state code (used for real state flag URLs).
const US_STATES: Record<string, string> = {
  alabama: "al",
  alaska: "ak",
  arizona: "az",
  arkansas: "ar",
  california: "ca",
  colorado: "co",
  connecticut: "ct",
  delaware: "de",
  florida: "fl",
  georgia: "ga",
  hawaii: "hi",
  idaho: "id",
  illinois: "il",
  indiana: "in",
  iowa: "ia",
  kansas: "ks",
  kentucky: "ky",
  louisiana: "la",
  maine: "me",
  maryland: "md",
  massachusetts: "ma",
  michigan: "mi",
  minnesota: "mn",
  mississippi: "ms",
  missouri: "mo",
  montana: "mt",
  nebraska: "ne",
  nevada: "nv",
  newhampshire: "nh",
  newjersey: "nj",
  newmexico: "nm",
  newyork: "ny",
  northcarolina: "nc",
  northdakota: "nd",
  ohio: "oh",
  oklahoma: "ok",
  oregon: "or",
  pennsylvania: "pa",
  rhodeisland: "ri",
  southcarolina: "sc",
  southdakota: "sd",
  tennessee: "tn",
  texas: "tx",
  utah: "ut",
  vermont: "vt",
  virginia: "va",
  washington: "wa",
  westvirginia: "wv",
  wisconsin: "wi",
  wyoming: "wy",
  washingtondc: "dc",
};

// U.S. cities → their state code so city origins also show the state flag.
const US_CITY_TO_STATE: Record<string, string> = {
  newyork: "ny",
  "newyork,usa": "ny",
  boston: "ma",
  chicago: "il",
  seattle: "wa",
  miami: "fl",
  sanfrancisco: "ca",
  losangeles: "ca",
  memphis: "tn",
  louisville: "ky",
  atlanta: "ga",
  dallas: "tx",
  houston: "tx",
  denver: "co",
  phoenix: "az",
  portland: "or",
  lasvegas: "nv",
  detroit: "mi",
  philadelphia: "pa",
  charlotte: "nc",
  austin: "tx",
  nashville: "tn",
  cincinnati: "oh",
  saltlakecity: "ut",
  jacksonville: "fl",
  kansascity: "mo",
  indianapolis: "in",
  columbus: "oh",
  minneapolis: "mn",
  neworleans: "la",
  pittsburgh: "pa",
  stlouis: "mo",
  saintlouis: "mo",
  sandiego: "ca",
  sanantonio: "tx",
  cleveland: "oh",
  milwaukee: "wi",
  baltimore: "md",
  richmond: "va",
  raleigh: "nc",
  fayetteville: "nc",
  savannah: "ga",
  orlando: "fl",
  tampa: "fl",
  toledo: "oh",
  norwalk: "oh",
  youngstown: "oh",
  erie: "pa",
  jamestown: "ny",
  buffalo: "ny",
  rochester: "ny",
  syracuse: "ny",
  albany: "ny",
  mobile: "al",
  pensacola: "fl",
  tallahassee: "fl",
};

const LEGACY_COUNTRY_CODES: Record<string, string> = {
  india: "IN",
  germany: "DE",
  france: "FR",
  canada: "CA",
  china: "CN",
  australia: "AU",
  nigeria: "NG",
  london: "GB",
  heathrow: "GB",
  jordan: "JO",
  damascus: "SY",
  paris: "FR",
  berlin: "DE",
  toronto: "CA",
  vancouver: "CA",
  sydney: "AU",
  melbourne: "AU",
  delhi: "IN",
  kolkata: "IN",
  madrid: "ES",
  barcelona: "ES",
  rome: "IT",
  milan: "IT",
  amsterdam: "NL",
  rotterdam: "NL",
  zurich: "CH",
  geneva: "CH",
  oslo: "NO",
  stockholm: "SE",
  copenhagen: "DK",
  helsinki: "FI",
  warsaw: "PL",
  prague: "CZ",
  budapest: "HU",
  vienna: "AT",
  brussels: "BE",
  lisbon: "PT",
  athens: "GR",
  dublin: "IE",
  bangladesh: "BD",
  singapore: "SG",
  dubai: "AE",
  oman: "OM",
  yemen: "YE",
  syria: "SY",
  istanbul: "TR",
  tokyo: "JP",
  beijing: "CN",
  riodejaneiro: "BR",
  capetown: "ZA",
  mexicocity: "MX",
  buenosaires: "AR",
};

const normalize = (s: string) => (s || "").replace(/\s+/g, "").toLowerCase();

export const stateCodeOf = (location?: string): string | undefined => {
  if (!location) return undefined;
  const key = normalize(location);
  return US_STATES[key] ?? US_CITY_TO_STATE[key];
};

export const countryCodeOf = (location?: string): string | undefined => {
  if (!location) return undefined;
  const key = normalize(location);
  if (US_STATES[key] || US_CITY_TO_STATE[key]) return undefined;
  if (LOCATION_COORDS[key]) return "US";
  return LEGACY_COUNTRY_CODES[key];
};

export const flagSrc = (location?: string): string | undefined => {
  if (!location) return undefined;
  const st = stateCodeOf(location);
  if (st) return `https://flags.telco.dev/us/${st}/${st}_48x32.png`;
  const cc = countryCodeOf(location);
  if (cc) return `https://flagcdn.com/24x18/${cc.toLowerCase()}.png`;
  return undefined;
};